# Plugins and prompt (plugins come from pacman). The order is tested and matters:
# syntax highlighting goes after everything else that touches the input line,
# and history substring search goes right after it.

# Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HISTORY_IGNORE="?(#c50,)"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=100

# fzf: Ctrl+R history, Ctrl+T files, Alt+C directories
source /usr/share/fzf/key-bindings.zsh

# Starship prompt
# Colors generated by matugen (falls back to ~/.config/starship.toml if the file is missing; comment out the next line to disable)
[[ -f ~/.config/matugen/generated/starship.toml ]] && export STARSHIP_CONFIG=~/.config/matugen/generated/starship.toml
eval "$(starship init zsh)"

# zoxide: "z <dir>" jumps to frequently used directories (also feeds yazi's Z)
eval "$(zoxide init zsh)"

# Syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
