
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

require("modules.monitors")
local programs = require("modules.programs")

require("modules.autostart")
require("modules.env")
require("modules.permissions")

-----------------------
---- LOOK AND FEEL ----
-----------------------
require("modules.appearance")
require("modules.animations")
require("modules.layouts")

require("modules.misc")
require("modules.input")
require("modules.keybindings")
require("modules.windowrules")
