import os

# Keep the settings changed via :set and :bind (autoconfig.yml is not loaded once config.py exists)
config.load_autoconfig()

# Web pages: ask sites for their dark variant (sites without one stay light); applied after a restart
c.colors.webpage.preferred_color_scheme = "dark"

# Colors generated by matugen (comment out this line to use the qutebrowser default colors)
config.source(os.path.expanduser("~/.config/matugen/generated/qutebrowser-colors.py"))
