-- Generated by matugen from .config/matugen/templates/hypr-colors.lua, do not edit by hand
return {
    active_border = "rgba({{colors.primary.default.hex_stripped}}ff)",
    inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}66)",
}
